using Autodesk.Authentication;
using Autodesk.Authentication.Model;
using Autodesk.SDKManager;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace AccC3DMetadata
{
    /// <summary>
    /// Wraps the Autodesk Authentication SDK to provide 3-legged OAuth PKCE token acquisition
    /// and silent token refresh for the plugin.
    /// </summary>
    public class AuthService
    {
        private readonly AuthenticationClient _authClient;

        /// <summary>
        /// OAuth 2.0 scopes requested for all tokens.  Must cover both Data Management (hub/project
        /// navigation) and the BIM 360 Document Management API (custom attribute read/write).
        /// </summary>
        private static readonly List<Scopes> _scopes = new()
        {
            Scopes.DataRead,    // Read hubs, projects, folders, and items via the Data Management API.
            Scopes.DataWrite,   // Required for future write operations against Data Management endpoints.
            Scopes.AccountRead, // Read account and hub metadata.
            Scopes.BucketRead,  // Read OSS bucket contents (used for config file download via the OSS API).
            Scopes.BucketCreate,
            Scopes.ViewablesRead
        };

        /// <summary>
        /// Initialises the service by building the Autodesk SDK manager and creating the
        /// <see cref="AuthenticationClient"/>.
        /// </summary>
        public AuthService()
        {
            var sdkManager = SdkManagerBuilder.Create().Build();
            _authClient = new AuthenticationClient(sdkManager);
        }

        /// <summary>
        /// Silently exchanges a refresh token for a new access token without opening the browser.
        /// </summary>
        /// <param name="clientId">The application's OAuth client ID.</param>
        /// <param name="refreshToken">The refresh token from the previous token response.</param>
        /// <returns>A new <see cref="ThreeLeggedToken"/> containing fresh access and refresh tokens.</returns>
        public async Task<ThreeLeggedToken> RefreshAsync(string clientId, string refreshToken)
            // clientSecret is null for public (PKCE) clients — the SDK accepts null here.
            => await _authClient.RefreshTokenAsync(clientId, null, refreshToken, _scopes)
                .ConfigureAwait(false);

        /// <summary>
        /// Performs a complete 3-legged OAuth PKCE authorisation flow:
        /// opens the system browser, listens on the loopback redirect URI for the auth code,
        /// then exchanges the code for tokens using the SDK.
        /// </summary>
        /// <param name="clientId">The application's OAuth client ID.</param>
        /// <param name="codeChallenge">
        /// The SHA-256 base64url hash of the PKCE code verifier, generated by the caller.
        /// </param>
        /// <param name="codeVerifier">
        /// The original random PKCE code verifier string — kept secret by the caller and sent
        /// only during the token exchange, not through the browser.
        /// </param>
        /// <param name="redirectUri">
        /// The loopback HTTP URI that the auth server will redirect to after authorisation
        /// (e.g. <c>http://localhost:8080/</c>).
        /// </param>
        /// <returns>A <see cref="ThreeLeggedToken"/> containing the access and refresh tokens.</returns>
        /// <exception cref="ArgumentNullException">
        /// <paramref name="clientId"/> or <paramref name="redirectUri"/> is null or whitespace.
        /// </exception>
        /// <exception cref="InvalidOperationException">
        /// The system browser could not be launched, or the authorisation server returned an error.
        /// </exception>
        /// <exception cref="TimeoutException">
        /// The user did not complete authorisation within 2 minutes.
        /// </exception>
        public async Task<ThreeLeggedToken> GetThreeLeggedTokenAsync(
            string clientId, string codeChallenge, string codeVerifier, string redirectUri)
        {
            if (string.IsNullOrWhiteSpace(clientId))
                throw new ArgumentNullException(nameof(clientId));
            if (string.IsNullOrWhiteSpace(redirectUri))
                throw new ArgumentNullException(nameof(redirectUri));

            // Build the authorization URL using the SDK — this includes the PKCE challenge
            // and all required query parameters.
            string authorizeUrl = _authClient.Authorize(
                clientId,
                ResponseType.Code,
                redirectUri,
                _scopes,
                codeChallengeMethod: "S256",
                codeChallenge: codeChallenge);

            string authorizationCode;

            // Start the loopback listener BEFORE opening the browser to avoid a race condition
            // where the browser redirects before the listener is ready.
            using (var listener = new HttpListener())
            {
                // HttpListener requires a trailing slash on the prefix.
                var prefix = redirectUri.TrimEnd('/') + "/";
                listener.Prefixes.Add(prefix);
                listener.Start();

                try
                {
                    Process.Start(new ProcessStartInfo
                    {
                        FileName = authorizeUrl,
                        UseShellExecute = true // Required for the OS default browser to handle the URL.
                    });
                }
                catch
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        $"Unable to open the system browser. Open this URL manually:\n{authorizeUrl}");
                }

                // Wait for the browser redirect, with a 2-minute timeout to avoid hanging forever.
                var contextTask = listener.GetContextAsync();
                var completed = await Task.WhenAny(contextTask, Task.Delay(TimeSpan.FromMinutes(2)))
                    .ConfigureAwait(false);

                if (completed != contextTask)
                {
                    listener.Stop();
                    throw new TimeoutException("Timed out waiting for the authorisation callback.");
                }

                var context = await contextTask.ConfigureAwait(false);

                // Send a friendly completion page to the browser — best-effort, never fatal.
                try
                {
                    const string html =
                        "<html><body><h2>Authentication complete. You may close this window.</h2></body></html>";
                    byte[] buffer = Encoding.UTF8.GetBytes(html);
                    context.Response.ContentType = "text/html";
                    context.Response.ContentLength64 = buffer.Length;
                    await context.Response.OutputStream.WriteAsync(buffer, 0, buffer.Length).ConfigureAwait(false);
                    context.Response.OutputStream.Close();
                }
                catch { /* Ignore — the page is cosmetic only. */ }

                // Extract the authorisation code (or propagate an error) from the redirect query string.
                string error = context.Request.QueryString["error"];
                if (!string.IsNullOrEmpty(error))
                {
                    listener.Stop();
                    throw new InvalidOperationException($"Authorisation error returned by the server: {error}");
                }

                authorizationCode = context.Request.QueryString["code"];
                if (string.IsNullOrEmpty(authorizationCode))
                {
                    listener.Stop();
                    throw new InvalidOperationException(
                        "The authorisation response did not contain a code.");
                }

                listener.Stop();
            }

            // Exchange the authorisation code for access + refresh tokens.
            // The code verifier is sent here (not during the browser step) — the server hashes it
            // and compares with the challenge to prove the caller holds the original secret.
            return await _authClient.GetThreeLeggedTokenAsync(
                clientId,
                authorizationCode,
                redirectUri,
                codeVerifier: codeVerifier)
                .ConfigureAwait(false);
        }
    }
}
